package ca.bc.gov.educ.api.student.profile.saga.constants;

public enum EventType {
  GET_STUDENT,
  CREATE_STUDENT,
  UPDATE_STUDENT,
  UPDATE_DIGITAL_ID,
  DELETE_STUDENT,
  UPDATE_PEN_REQUEST,
  NOTIFY_STUDENT_PEN_REQUEST_COMPLETE,
  MARK_SAGA_COMPLETE, INITIATED, ADD_PEN_REQUEST_COMMENT, GET_DIGITAL_ID, GET_PEN_REQUEST, ROLLBACK
}
