package ca.bc.gov.educ.api.student.profile.saga.constants;

public enum EventOutcome {
  STUDENT_FOUND,
  STUDENT_NOT_FOUND,
  STUDENT_CREATED,
  STUDENT_UPDATED,
  STUDENT_PROFILE_UPDATED,
  DIGITAL_ID_UPDATED,
  DIGITAL_ID_NOT_FOUND,
  INITIATE_SUCCESS, STUDENT_NOTIFIED, PROFILE_REQUEST_COMMENT_ADDED, PROFILE_REQUEST_COMMENT_ALREADY_EXIST, DIGITAL_ID_FOUND, STUDENT_PROFILE_FOUND,
  NOTIFY,STUDENT_PROFILE_NOT_FOUND
}
