package ca.bc.gov.educ.api.student.profile.saga.constants;

public enum EventOutcome {
  STUDENT_FOUND,
  STUDENT_NOT_FOUND,
  STUDENT_CREATED,
  STUDENT_UPDATED,
  PEN_REQUEST_UPDATED,
  DIGITAL_ID_UPDATED,
  DIGITAL_ID_NOT_FOUND,
  INITIATE_SUCCESS, PEN_REQUEST_UPDATE_FAILED, STUDENT_NOTIFIED, PEN_REQUEST_COMMENT_ADDED, PEN_REQUEST_COMMENT_ALREADY_EXIST, DIGITAL_ID_FOUND, PEN_REQUEST_FOUND, PEN_REQUEST_NOT_FOUND
}
