package ca.bc.gov.educ.api.student.profile.saga.constants;

public enum SagaEnum {
  STUDENT_PROFILE_COMPLETE_SAGA,
  STUDENT_PROFILE_COMMENTS_SAGA,
  STUDENT_PROFILE_REJECT_SAGA,
  STUDENT_PROFILE_RETURN_SAGA,
  PEN_REQUEST_COMPLETE_SAGA,
  PEN_REQUEST_COMMENTS_SAGA,
  PEN_REQUEST_RETURN_SAGA,
  PEN_REQUEST_REJECT_SAGA,
  PEN_REQUEST_UNLINK_SAGA
}
