package ca.bc.gov.educ.api.student.profile.saga.constants;

public enum SagaTopicsEnum {
  STUDENT_API_TOPIC,
  STUDENT_PROFILE_COMPLETE_SAGA_TOPIC,
  STUDENT_PROFILE_COMMENTS_SAGA_TOPIC,
  DIGITAL_ID_API_TOPIC,
  STUDENT_PROFILE_API_TOPIC,
  STUDENT_PROFILE_EMAIL_API_TOPIC,
  STUDENT_PROFILE_REQUEST_REJECT_SAGA_TOPIC
}
