ALTER TABLE STUDENT_PROFILE_SAGA ADD COLUMN PROFILE_REQUEST_ID uuid;
ALTER TABLE STUDENT_PROFILE_SAGA ADD COLUMN PEN_REQUEST_ID uuid;
CREATE INDEX STUDENT_PROFILE_SAGA_PEN_REQUEST_ID_IDX ON STUDENT_PROFILE_SAGA (PEN_REQUEST_ID);
CREATE INDEX STUDENT_PROFILE_SAGA_PROFILE_REQUEST_ID_IDX ON STUDENT_PROFILE_SAGA (PROFILE_REQUEST_ID);
