ALTER TABLE STUDENT_PROFILE_SAGA ALTER COLUMN CREATE_USER TYPE varchar(100);
ALTER TABLE STUDENT_PROFILE_SAGA ALTER COLUMN UPDATE_USER TYPE varchar(100);

ALTER TABLE STUDENT_PROFILE_SAGA_EVENT_STATES ALTER COLUMN CREATE_USER TYPE varchar(100);
ALTER TABLE STUDENT_PROFILE_SAGA_EVENT_STATES ALTER COLUMN UPDATE_USER TYPE varchar(100);

