ALTER TABLE STUDENT_PROFILE_SAGA
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );

ALTER TABLE STUDENT_PROFILE_SAGA_EVENT_STATES
MODIFY (
           CREATE_USER VARCHAR2(100),
           UPDATE_USER VARCHAR2(100)
       );
