---
apiVersion: template.openshift.io/v1
kind: Template
labels: 
  template: student-profile-saga-api-pipeline
metadata: 
  name: student-profile-saga-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "student-profile-saga-api-pipeline"
  spec:
    source:
      git:
        ref: master
        uri: 'https://github.com/bcgov/EDUC-STUDENT-PROFILE-SAGA-API'
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile